### ISSUE TITLE
3D Keypoint data?

### ISSUE THREAD

**Issue by renchsan** [statho/ScoreHMR#10]
Hi,
Can 3D keypoint data be returned in json format from images and videos?
Only see 2d keypoints return from images and videos using the demo scripts. TIA

**Comment by statho** [comment]
You can get the 3D keypoints as `smpl_out.joints`, where `smpl_out` is the output of the SMPL model (see [here](https://github.com/statho/ScoreHMR/blob/master/demo_image.py#L174) for an example).

**Comment by renchsan** [comment]
Great, this returns the Openpose joints and ground truth joints, thanks!

**Comment by wclincke** [comment]
Hi,
After extracting 3D keypoints from images, I'm looking to visualize them as a skeleton overlay on the images. Could you point me toward resources or documentation that explain the 3D keypoints to skeleton point mappings?
Thanks for your help!

**Comment by statho** [comment]
The definition for the SMPL joints can be found [here](https://github.com/statho/ScoreHMR/blob/master/constants.py#L75) (also see image below).
![SMPL_joints](https://github.com/statho/ScoreHMR/assets/20449800/22ecc589-7ed5-4ed5-bc67-02843080ba58)

To visualize the keypoints you can project them onto an image, using [this](https://github.com/statho/ScoreHMR/blob/master/score_hmr/utils/geometry.py#L82) function.

**Comment by wclincke** [comment]
Is this the initial set of 24 points from the smpl_out.joints output? It seems that this output provides 44 3D data points.
