### ISSUE TITLE
SMPLx version

### ISSUE THREAD

**Issue by GrigorySamokhin** [statho/ScoreHMR#11]
Hello! Thanks for your amazing work! Im interested in applying this code to the smplx model, so, can you give any recommendations? or do you have such plans, or have you had some difficulties?

**Comment by statho** [comment]
Thanks for appreciating our work! We did not experiment with the SMPL-X model, and this is not in our current plans. 

If you want to use ScoreHMR with SMPL-X, training the diffusion model with  [ExPose](https://github.com/vchoutas/expose) predictions as pseudo ground-truth could be a good start.
