### ISSUE TITLE
Smoothing doesn't work

### ISSUE THREAD

**Issue by tsoydari** [statho/ScoreHMR#14]
Thanks for your work! Very interesting article. 
But when testing the provided weights, there is no difference between the results of 4D-Humans and ScoreHMR. The shaking does not go away, especially in the feet.

https://github.com/statho/ScoreHMR/assets/72319918/6285ad29-1537-401e-a15b-35255607a403

On the attached video there are, in order: 4D-Humans, ScoreHMR with default parameters and 1000 iterations of ScoreHMR. Why is there no difference?

**Comment by statho** [comment]
You can increase smoothing by increasing the `W_SMOOTH` value [here](https://github.com/statho/ScoreHMR/blob/master/score_hmr/configs/base.yaml#L55).

In the demo, code we use keypoint detections from ViTPose, which do not detect keypoints on the feet and hands of a person. You could use keypoints from OpenPose if you'd like the model to fit better on the hands and feet.

**Comment by Sun-Happy-YKX** [comment]
> You can increase smoothing by increasing the `W_SMOOTH` value [here](https://github.com/statho/ScoreHMR/blob/master/score_hmr/configs/base.yaml#L55).
> 
> In the demo, code we use keypoint detections from ViTPose, which do not detect keypoints on the feet and hands of a person. You could use keypoints from OpenPose if you'd like the model to fit better on the hands and feet.

Hello, could you share me the reasonable value range of W_SMOOTH?

**Comment by statho** [comment]
You can try values between 10 and 70 for W_SMOOTH.
