### ISSUE TITLE
no hmr2 - where to find it 

### ISSUE THREAD

**Issue by jakhon37** [statho/ScoreHMR#16]
hello 
thank you for your wonderful job 

i could not find hmr2 package when running demo 
where can i get it ? 

from hmr2.configs import CACHE_DIR_4DHUMANS
from hmr2.models import download_models, load_hmr2, DEFAULT_CHECKPOINT
from hmr2.utils import recursive_to
from hmr2.utils.renderer import Renderer, cam_crop_to_full

or is it customized  code from hmr2.0 repo? (https://github.com/russoale/hmr2.0/tree/master?tab=readme-ov-file)
if so can you share it ?

**Comment by statho** [comment]
The hmr2 package is the HMR 2.0 model from [4D-Humans](https://github.com/shubham-goel/4D-Humans) and it should be automatically installed when installing PHALP (this is done [here](https://github.com/statho/ScoreHMR/blob/master/install_environment.sh#L14) in the installation script).

Can you provide more details on the issue you're facing (maybe send me the error message)?

**Comment by jakhon37** [comment]
i found PHALP requires [Neural 3D Mesh Renderer ](https://github.com/shubham-goel/NMR) package and installs it automatically 
but for some reason NMR is installing cpu version of torch and giving cuda not found error then PHALP installation left incomplete 
so i installed gpu version of torch manually 
now it is all set and working normal 
thank you
