### ISSUE TITLE
OSX compatibility 

### ISSUE THREAD

**Issue by gurkirt** [statho/ScoreHMR#17]
Is it possible to use proposed refinement with the predictions from OSX model. OSX seems quite generisable model. It would be cool to have a demo where refinement is applied on osx output. Or would it require further fine tuning on predictions of osx.

thank you for the great work!
Cheers 
Gurkirt

**Comment by statho** [comment]
Thanks for appreciating our work! ScoreHMR does not use an expressive model for the face and hands.

If you want to run refinement on top of OSX, you would need to train ScoreHMR with [SMPL-X](https://smpl-x.is.tue.mpg.de/) fits. Training the diffusion model with [SMPLer-X](https://github.com/caizhongang/SMPLer-X) predictions as pseudo ground-truth could be a good start.

**Comment by gurkirt** [comment]
Thank you for quick reply, much appreciated! What if I convert SMPL-X outputs from OSX to SMPL usiunfg revese mapping defined [here](https://github.com/vchoutas/smplx/blob/main/transfer_model/docs/transfer.md), then it should work without any training right?

**Comment by statho** [comment]
Yes, it should work.

**Comment by TDIT-haha** [comment]
> Thank you for quick reply, much appreciated! What if I convert SMPL-X outputs from OSX to SMPL usiunfg revese mapping defined [here](https://github.com/vchoutas/smplx/blob/main/transfer_model/docs/transfer.md), then it should work without any training right?

May I ask if you have achieved it? Can you share it with me for reference?
