### ISSUE TITLE
UnFit Effect on Depth？

### ISSUE THREAD

**Issue by Sun-Happy-YKX** [statho/ScoreHMR#20]
The visual effect in front view is well, but in vertical view does not works. The distance in xy-axis and in z-axis(depth) are obviously not fit. @statho 
![image](https://github.com/statho/ScoreHMR/assets/50354191/aeddfeea-1a31-48ab-91c2-55fef08f80e4)

**Comment by statho** [comment]
Is it possible to send me your video, so I can give it a try from my side?

**Comment by Sun-Happy-YKX** [comment]
> Is it possible to send me your video, so I can give it a try from my side?

Hello, in my implementation for a lot video, I figure out that the varying range of depth is obviously larger than x/y axis. (x/t axis is about 2, depth is about 5+)

**Comment by exel-dot** [comment]
@Sun-Happy-YKX Can i ask you about something? Please give me your contact.
