### ISSUE TITLE
2D Annotations from OpenPose or SPIN/EFT

### ISSUE THREAD

**Issue by USTCWzy** [statho/ScoreHMR#27]
Hello! I am somewhat confused. On P6, you mentioned that the 2D keypoints are detected by Openpose, but later on, you emphasize that the actual pose annotations come from SPIN/EFT. Could you kindly clarify which annotations you specifically used during the body model fitting process? Thank you very much!

**Comment by statho** [comment]
Hello! The SPIN/EFT fits are used for training the diffusion model. They are pseudo-GT SMPL parameters for the corresponding images. We use 2D keypoint detections from OpenPose for model-fitting experiments, which corresponds to test-time processing (i.e., improve the regression estimate given 2D OpenPose keypoint detections).
