### ISSUE TITLE
About Multiview Demo

### ISSUE THREAD

**Issue by dangdang2222** [statho/ScoreHMR#28]
Dear Author,

Thank you for your great work. 
I am trying to apply your work in multi-view dataset, but struggling in loading data. 
I wonder if is it possible for you to provide a small example of loading multiview dataset demo code.

**Comment by statho** [comment]
Hello! We don't plan on releasing a demo for this part. To run on your own dataset you can edit [BatchedImageDataset](https://github.com/statho/ScoreHMR/blob/f623ed1f83441fdcacdbdc2a87b72c015b880d34/score_hmr/datasets/batched_image_dataset.py#L16) class. 

The class expects the data to be in a ```.pkl```  file containing the path and the bounding box of each person, and are grouped for all available views of each subject:  

```
import pickle
data = pickle.load(open(<dataset_name>.pkl, "rb"))
data = [
  {
   "imgname":  np.array(num_views),      # paths for num_views images for person 1
   "center"     : np.array(num_views, 2),   # center for the bounding box for person 1 in each of the views
   "scale"      : np.array(num_views),        # scale for the bounding box for person 1 in each of the views
  },
  ...  # same of person 2, 3, ...
]
```
You can load the data with [BatchedImageDataset](https://github.com/statho/ScoreHMR/blob/f623ed1f83441fdcacdbdc2a87b72c015b880d34/score_hmr/datasets/batched_image_dataset.py#L16), perform inference with a regression network to get the initial regression estimates, and then run multi-view refinement with ScoreHMR similar to the ```eval/eval_multiview.py``` script.
