### ISSUE TITLE
"pip install phalp[all]@git+https://github.com/brjathu/PHALP.git". failed~~!

### ISSUE THREAD

**Issue by 2022yingjie** [statho/ScoreHMR#29]
Hi, thank you for your impressive work. When I want to run demo on my own machine, the configuration process exists some problems. The detailed information is shown as follows:

```
pip install phalp[all]@git+https://github.com/brjathu/PHALP.git
Looking in indexes: http://yum.tbsite.net/pypi/simple
Collecting phalp@ git+https://github.com/brjathu/PHALP.git (from phalp[all]@ git+https://github.com/brjathu/PHALP.git)
  Cloning https://github.com/brjathu/PHALP.git to /tmp/pip-install-x2n0n0kz/phalp_0dd54645d9564485895a5f9f6902704b
  Running command git clone --filter=blob:none --quiet https://github.com/brjathu/PHALP.git /tmp/pip-install-x2n0n0kz/phalp_0dd54645d9564485895a5f9f6902704b
  Resolved https://github.com/brjathu/PHALP.git to commit 677074a9bd7acac58c0b98a31b04ae54b93dcd2f
  Preparing metadata (setup.py) ... done
Collecting detectron2@ git+https://github.com/facebookresearch/detectron2.git (from phalp@ git+https://github.com/brjathu/PHALP.git->phalp[all]@ git+https://github.com/brjathu/PHALP.git)
  Cloning https://github.com/facebookresearch/detectron2.git to /tmp/pip-install-x2n0n0kz/detectron2_51ea0ad3710740699c02239a688dc903
  Running command git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-install-x2n0n0kz/detectron2_51ea0ad3710740699c02239a688dc903
  fatal: unable to access 'https://github.com/facebookresearch/detectron2.git/': GnuTLS recv error (-110): The TLS connection was non-properly terminated.
  error: subprocess-exited-with-error
  
  × git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-install-x2n0n0kz/detectron2_51ea0ad3710740699c02239a688dc903 did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git clone --filter=blob:none --quiet https://github.com/facebookresearch/detectron2.git /tmp/pip-install-x2n0n0kz/detectron2_51ea0ad3710740699c02239a688dc903 did not run successfully.
│ exit code: 128
╰─> See above for output.
```

I have no idea to solve it, is it a network issue? or depencies I need to install. 
Thank your very much.

**Comment by statho** [comment]
Hello! The error you're encountering suggests that the pip command failed to clone the ```detectron2``` repository, which is a dependency of ```PHALP```, from GitHub due to a TLS connection issue. This seems like a network-related problem rather than a problem with pip or the repository itself.

You can try to manually clone the repo and then install it:
```
git clone https://github.com/brjathu/PHALP.git
cd PHALP
pip install -e .[all]
```

If you run into the same issue with ```detectron2```, you can manually clone that repository as well and install it:
```
git clone https://github.com/facebookresearch/detectron2.git
cd detectron2
pip install -e .
```

Finally, follow the same for other dependencies.

**Comment by 2022yingjie** [comment]
> Hello! The error you're encountering suggests that the pip command failed to clone the `detectron2` repository, which is a dependency of `PHALP`, from GitHub due to a TLS connection issue. This seems like a network-related problem rather than a problem with pip or the repository itself.
> 
> You can try to manually clone the repo and then install it:
> 
> ```
> git clone https://github.com/brjathu/PHALP.git
> cd PHALP
> pip install -e .[all]
> ```
> 
> If you run into the same issue with `detectron2`, you can manually clone that repository as well and install it:
> 
> ```
> git clone https://github.com/facebookresearch/detectron2.git
> cd detectron2
> pip install -e .
> ```
> 
> Finally, follow the same for other dependencies.

Thank you it works for me
