### ISSUE TITLE
About Data File

### ISSUE THREAD

**Issue by luoxue-star** [statho/ScoreHMR#32]
Hi, Thanks for your excellent work!
How were the four files, betas_stats_eft_fits.npz,betas_stats_spin_fits.npz, pare_feat_stats.npz, and prohmr_feat_stats.npz, obtained? @statho 
Thanks and best wishes!

**Comment by RammusLeo** [comment]
+1. Have you figured out this issue?

**Comment by statho** [comment]
The values in those files are calculated over the training datasets.

**Comment by luoxue-star** [comment]
Does that mean calculating the corresponding features from the training set and calculating the mean and standard deviation for those features?

**Comment by statho** [comment]
Exactly. We found out that using unnormalized values for SMPL betas works well too, so no need to compute statistics for SMPL betas.

**Comment by luoxue-star** [comment]
Thanks for your reply!
