### ISSUE TITLE
6d pose representation

### ISSUE THREAD

**Issue by smandava98** [statho/ScoreHMR#6]
Hi,

I have one more question:

If you are converting to 6d poses and you are converting it back to rotation matrices how do you ensure that the final matrices are still valid? As far as I know, wouldnt this affect how it is displayed in the image?

**Comment by statho** [comment]
Please have a look at [this](https://github.com/statho/ScoreHMR/blob/master/score_hmr/utils/geometry.py#L64) function. It converts the 6D poses to a valid rotation matrices.

**Comment by statho** [comment]
Just to make sure.
a) Are you using the [prepare_smpl_params](https://github.com/statho/ScoreHMR/blob/master/score_hmr/utils/utils.py#L75) function that internally converts the 6D poses to rotation matrices before running the SMPL model?
b) Are rotating the x-axis by 180 degrees before rendering, as done [here](https://github.com/statho/ScoreHMR/blob/master/score_hmr/utils/mesh_renderer.py#L227)?

**Comment by statho** [comment]
Please have a look at how we convert to 6D pose [here](https://github.com/statho/ScoreHMR/blob/master/score_hmr/diffusion.py#L178). You will only need to omit the `aa_to_rotmat()` function call, if rotation matrices are used for the pose.

Please convert the rotation matrices to 6D, as we do in the highlighted code.
