### ISSUE TITLE
Typo in ScoreHMR.ipynb show_local_mp4_video

### ISSUE THREAD

**Issue by atonalfreerider** [statho/ScoreHMR#8]
When the video display runs for breakdancing.mp4, it is looking for a file at 
demo_out/videos/breakdancing.mp4: No such file or directory

The actual file name has a shot incrementer appended to the end, so the filename for the video to play is:
demo_out/videos/breakdancing_0.mp4

**Comment by statho** [comment]
Thanks a lot for catching this! Fixed the error now.
