### ISSUE TITLE
fail to run demo_video.py

### ISSUE THREAD

**Issue by zhaomingBDAI** [statho/ScoreHMR#9]
Hi, 

I am trying to run the demo code with 

`python demo_video.py     --input_video example_data/videos/breakdancing.mp4     --out_folder demo_out/videos`

But I got the following error:

> [2024-03-25 17:39:30,875][phalp.trackers.PHALP][INFO] - Setting up Visualizer...
> [2024-03-25 17:39:31,824][phalp.trackers.PHALP][INFO] - Setting up DeepSort...
> [2024-03-25 17:39:31,825][phalp.trackers.PHALP][INFO] - Saving tracks at : demo_out/videos/phalp_out/breakdancing/results/breakdancing
> list index out of range
> Traceback (most recent call last):
>   File "miniconda3/envs/score_hmr/lib/python3.10/site-packages/phalp/trackers/PHALP.py", line 174, in track
>     list_of_shots = self.get_list_of_shots(list_of_frames)
>   File "miniconda3/envs/score_hmr/lib/python3.10/site-packages/phalp/trackers/PHALP.py", line 610, in get_list_of_shots
>     if(isinstance(list_of_frames[0], str)):
> IndexError: list index out of range

Any help is appreciated! Thanks.

**Comment by statho** [comment]
There seems to be an issue when loading the extracted frames from the input video. Can you check the content of `list_of_frames`?

**Comment by gokcergun** [comment]
Hi, I have the same error, and yes the list_of_frames return empty. How can I fix it? 
By the way, I had also an import error related to neural_renderer. I fixed it by changing the line 

  #phalp_tracker = HMR2_4dhuman(cfg)
    phalp_tracker = PHALP_Prime_HMR2(cfg)
as explained here: https://github.com/statho/ScoreHMR/issues/7

**Comment by Mudhdhoo** [comment]
Did anyone find a fix for this?

**Comment by statho** [comment]
Probably the frames from the video are not extracted or extracted in the wrong directory, that is why `list_of_frames` is empty. For the provided video, the extracted frames should be in `demo_out/videos/images/breakdancing/`. Can you verify that the images are indeed extracted in that directory?
